### ISSUE TITLE
Twitch Chat Downloader

### ISSUE THREAD

**Issue by PetterKraabol** [MrBrax/twitch-vod-chat#1]
Hi, I just found this repo!

Twitch Chat Downloader switched to [New Twitch API for video data](https://dev.twitch.tv/docs/api/reference/#get-videos), which makes it incompatible with your parsing.

TCD is now available via `pip install tcd` and to download json data, you'd run `tcd -v {id} --format json`.

**Comment by MrBrax** [comment]
I'm gonna take a look at this, if people are interested now.

**Comment by MrBrax** [comment]
Should be fixed in newest commit.
