### ISSUE TITLE
Stop button isn't working

### ISSUE THREAD

**Issue by Myaukolka** [MrBrax/twitch-vod-chat#18]
Stop button pauses chat but not the video. Resuming is only possible via progress bar.
Also spacebar does nothing regardless if focused/fullscreen or not.

**Comment by MrBrax** [comment]
yeah, i'm gonna rewrite the controls, the original version was only meant to be for recording and not playback, so i never put in any effort to be able to seek/pause

**Comment by MrBrax** [comment]
added some simple seeking with arrow keys too, let me know if it all works

**Comment by Myaukolka** [comment]
> added some simple seeking with arrow keys too, let me know if it all works

All good thank you for your work, amazing tool. 👍
