### ISSUE TITLE
[Suggestion] Chat at side instead of in video

### ISSUE THREAD

**Issue by TheDoctor40** [MrBrax/twitch-vod-chat#19]
I have a suggestion for an option; 
A toggle to put the chat on the side next to the video instead of in the video. There is a fork which claims to do this, but it doesn't work for me, but I don't have the technical knowhow to do it myself.

**Comment by MrBrax** [comment]
i guess that could technically be possible without a lot of work, i'll consider it

**Comment by MrBrax** [comment]
check that out how it works

implementation kinda sucks, it's locked to 16:9 since i couldn't find a good way to limit the comments div height without a static parent height

**Comment by MrBrax** [comment]
added a forced ultrawide mode
