### ISSUE TITLE
It seems the emotes showing is broken

### ISSUE THREAD

**Issue by inkforest** [MrBrax/twitch-vod-chat#2]
If I tick the Emotes in the Chat style box, only those only emotes chats will be showed:
<img src="https://s2.ax1x.com/2019/08/05/eccjQH.png" alt="eccjQH.png" border="0" />
After cancel Emotes it's working but without emotes...

**Comment by inkforest** [comment]
BTW, I prefer left align when the chat is on right, so I think it would be better if the align can be changed by user.

**Comment by MrBrax** [comment]
Must be some change by twitch, that didn't happen when i initially created it. Gonna have to look into it.

**Comment by inkforest** [comment]
Thank you! :D It really helps a lot!! Now I can review my favorite VODs with chat even when they are deleted.
And I found that it is not difficult to edit the html code to suit my own habit so maybe you can forget the suggestion above :)

**Comment by EnterGin** [comment]
Hello! The problem remained unresolved. Do you have plans to continue the project?

**Comment by MrBrax** [comment]
Great that this project is getting some attention, but i kinda see it as failed, since you have to record the whole thing in realtime. If i can get a hold of a short vod with chat then maybe.

**Comment by EnterGin** [comment]
Sorry for late answer. Do you need short vod with new api chat? I have some. Check it out: https://drive.google.com/drive/folders/1q-_QLccSPMlMO8lQIp0USF9tZYSNccTD?usp=sharing

**Comment by MrBrax** [comment]
oh wow, seems like i had changed a lot of stuff but never committed the changes, check the new one out

**Comment by EnterGin** [comment]
That's really good! Works just fine.
What about badges? Is it possible to make them like on a twitch?

**Comment by MrBrax** [comment]
Badges? Is that something new? I don't look at chat too often.

**Comment by EnterGin** [comment]
![image](https://user-images.githubusercontent.com/51099894/67634992-02300480-f8d3-11e9-8df2-577211d538a8.png)
I'm about that. Not like on twitch
![image](https://user-images.githubusercontent.com/51099894/67635001-20960000-f8d3-11e9-8495-a7c8727763d0.png)

**Comment by MrBrax** [comment]
and it's done

**Comment by EnterGin** [comment]
Thanks a lot. I really appreciate your work.

**Comment by EnterGin** [comment]
And, if it doesn't bother you, it would be nice to make the pause button.

**Comment by EnterGin** [comment]
And the transition to a needed moment in the video. Sorry for the many wishes.

**Comment by MrBrax** [comment]
right click the video and show controls

**Comment by EnterGin** [comment]
Wow, in this version it works! Thank you twice. Really good job!

**Comment by MrBrax** [comment]
nice! feel free to post videos of this tool in use, so i can see feedback
