### ISSUE TITLE
[Suggestion] OBS browser feature?

### ISSUE THREAD

**Issue by migeru-san** [MrBrax/twitch-vod-chat#20]
Will it be possible to make this for the OBS browser? It could be a nice interaction with the live chat

**Comment by MrBrax** [comment]
i don't really see the point of it? this is a video player, unless you mean like showing a vod with chat on your livestream?

**Comment by migeru-san** [comment]
Just like Nico Nico Douga chat,  but as HTML, CSS JS, and offline (local) so it can be attached to OBS or other software.

I hope I am making sense.

**Comment by MrBrax** [comment]
so you want an old archived vod's comments to be shown on screen?

it previously used its own timer, but now i just attach it to the video stream, so it now requires a video

**Comment by migeru-san** [comment]
ORIGINAL PROJECT
https://github.com/joxcat/nico-chat-browser

This guy made for the browser source however but it ran thru his server *dead server*

however, Blankaex forked it so that I could run it locally on your PC, it works fine but it doesn't show emotes like yours is refine

check it out

https://github.com/blankaex/nico-chat-browser but it doesn't show emojis/emotes

maybe your could fork it and fix it?

**Comment by MrBrax** [comment]
So that thing shows **LIVE** Twitch chat in a browser source. This project is purely offline, with optional VOD chat fetching.

Having **LIVE** comments showing up is not something i have planned, and especially with something like the niconico mode (which has been removed since a while back), it would probably be too much work and out of scope.

**Comment by migeru-san** [comment]
I was wondering anyway your project is amazing!

**Comment by MrBrax** [comment]
Making a separate project for this is not out of the question though, especially since there's no need for API keys or anything if you just want chat messages showing up, but it's all about my interest in it and how many people want it.

**Comment by migeru-san** [comment]
Understood!
