### ISSUE TITLE
Chat replay not working as intended

### ISSUE THREAD

**Issue by KurtzPT** [MrBrax/twitch-vod-chat#22]
I tried to play a vod + chat downloaded with TwitchAutomator, the chat is not being show correctly, it only shows messages with ONE emote, no text or any message with more than one emote in it.

**Comment by MrBrax** [comment]
is this with the version bundled with twitchautomator? it seems to be working for me

**Comment by KurtzPT** [comment]
> is this with the version bundled with twitchautomator? it seems to be working for me

I actually used the dist version from here, since the player button was broken on my TA

**Comment by MrBrax** [comment]
i fixed that a few commits ago, try updating your instance since it's easier to have it play in there

**Comment by MrBrax** [comment]
this repo is a bit messed up like all my projects, i think there's a lot of unmerged code

**Comment by KurtzPT** [comment]
alright I'll try and check later on with TA updated from developed.

**Comment by KurtzPT** [comment]
I'm going to create an issue on TA instead, since I found some issues popping up there.
