### ISSUE TITLE
BTTV FFZ emotes

### ISSUE THREAD

**Issue by EnterGin** [MrBrax/twitch-vod-chat#3]
Is it possible to add BTTV and FFZ emotes?

**Comment by MrBrax** [comment]
last time i worked on this they worked

**Comment by EnterGin** [comment]
Oh sorry I mean gif emotes

**Comment by MrBrax** [comment]
yes, they should work too. they could have changed the api again however

**Comment by EnterGin** [comment]
So they don't work 🙃
![chrome_DWSQG9X4VA](https://user-images.githubusercontent.com/51099894/78716678-03f10000-7928-11ea-812a-bb9102fc3e7f.png)

**Comment by MrBrax** [comment]
![1586337379557](https://user-images.githubusercontent.com/1517911/78767126-798db800-798a-11ea-9d15-be5d01aa64ef.png)

works for me on a sodapoppin video. you're gonna have to supply a source vod (that's not massive), and which message isn't working

**Comment by EnterGin** [comment]
This for example. Every message has gif emotes.
[example.zip](https://github.com/MrBrax/twitch-vod-chat/files/4449700/example.zip)

**Comment by MrBrax** [comment]
it was a lowercase username error, i have fixed it, but sourcetree seems to have broken with github, gonna have to look for an alternative

**Comment by EnterGin** [comment]
OK. Good :)

**Comment by MrBrax** [comment]
finally fixed it, crappy software that is. added an experimental twitch embed when no video is selected too

**Comment by EnterGin** [comment]
Seems really good. Thanks

**Comment by EnterGin** [comment]
In newest version FFZ emoticons aren't loading.
![image](https://user-images.githubusercontent.com/51099894/79909195-379e5080-8425-11ea-8b48-577158648c1a.png)
![image](https://user-images.githubusercontent.com/51099894/79909243-500e6b00-8425-11ea-8b5a-e6763a17d22f.png)

**Comment by MrBrax** [comment]
post link of vod, looks like it's new

**Comment by EnterGin** [comment]
https://www.twitch.tv/videos/597569705

**Comment by MrBrax** [comment]
which method are you using? fully online is working for me

**Comment by EnterGin** [comment]
I'm tried also online. It's still doesn't working. But on old version it is working fine.
Also online video doesn't working for me on master, it is just freeze. On old version works fine. These two versions I use:
[twitch-vod-chat-old.zip](https://github.com/MrBrax/twitch-vod-chat/files/4514836/twitch-vod-chat-old.zip)

[twitch-vod-chat-master.zip](https://github.com/MrBrax/twitch-vod-chat/files/4514834/twitch-vod-chat-master.zip)

**Comment by MrBrax** [comment]
try downloading it again, just commited a fix for maybe another error, just to be sure

check the dev console also for any errors regarding vodplayer.js/ts, excluding the twitch calls

**Comment by EnterGin** [comment]
![image](https://user-images.githubusercontent.com/51099894/79961148-f773b800-848e-11ea-96f8-3d74540b5879.png)

**Comment by MrBrax** [comment]
you might need to run it from a webpage ( https://vod.dongers.net/player.html ) or your own local webserver because of CORS

**Comment by EnterGin** [comment]
![image](https://user-images.githubusercontent.com/51099894/79961283-268a2980-848f-11ea-92ab-0f3e22bdc1ce.png)

**Comment by EnterGin** [comment]
Oh, working fine from a webpage.

**Comment by MrBrax** [comment]
i see, ffz doesn't supply http/https protocol in their urls, so because you're running locally it breaks

**Comment by MrBrax** [comment]
pushed an update to fix it

**Comment by EnterGin** [comment]
Good, now it is working fine.
BTW online videos doesn't work while running locally

**Comment by MrBrax** [comment]
that would probably make sense, too many safeguards in place

**Comment by EnterGin** [comment]
But I don't really need this, 'cause I have all VODs 😂
Thanks for your hardwork 😉

**Comment by MrBrax** [comment]
yeah it wouldn't surprise me if online chat fetching would get you banned, so i'd use vod+json chat only.

**Comment by EnterGin** [comment]
Hello
Again some problem with it. BTTV cannot be fetched, so there are no chat at all. Tried also on your site, still doesn't work.

**Comment by MrBrax** [comment]
seems like their api is either deprecated or nonfunctioning, i'm having a look

**Comment by MrBrax** [comment]
bttv api has been upgraded to v3
