### ISSUE TITLE
[Suggestion] Make usage of the full page width.

### ISSUE THREAD

**Issue by KurtzPT** [MrBrax/twitch-vod-chat#33]
Using this with TwitchAutomator/LiveStreamDVR.

With minimal mode here, but without it it's the exact same: there's so much free space not being used and I don't have a way of using it.

![image](https://user-images.githubusercontent.com/14930057/168107253-bae47d24-0f1c-4774-b52f-7264fad54bcc.png)

Ultrawide also doesn't do anything besides removing the top space from what it seems.

Either make a setting to use the full page width or change the default behavior all together.

Another point is the fullscreen button doesn't do anything.

**Comment by MrBrax** [comment]
not sure why some things stopped working, i think because of the youtube api thing using promises now

i hacked together some fixes for them, but some things are still broken

the ultrawide is to be used with the chat not overlaid, seems to be working.
fullscreen now fixed, need to rewrite a lot though

**Comment by MrBrax** [comment]
some massive speed improvements now, probably still broke twitch/youtube embeds

**Comment by KurtzPT** [comment]
@MrBrax Is this updated on LiveStreamDVR? I was trying out and I cannot see the "Unlocked width" button:

![image](https://user-images.githubusercontent.com/14930057/169661842-69efb420-73ba-429f-9561-3ce2244c0f13.png)

**Comment by MrBrax** [comment]
i'm not sure how submodules work honestly, how to push it to everyone

**Comment by KurtzPT** [comment]
I never experimented with submodules. found this might help: 
https://gist.github.com/korya/9047870

It just seems the issue is that the submodule isn't pointing to master branch.

**Comment by MrBrax** [comment]
i think that did it, `git submodule update --remote --merge` and push commit

**Comment by KurtzPT** [comment]
I can see the button now, thanks!
