### ISSUE TITLE
Vod Chat not working anymore (LivesteamDVR)

### ISSUE THREAD

**Issue by CappiSteijns** [MrBrax/twitch-vod-chat#56]
Hello, 

Using LivesteamDVR on unraid. 

Since a short time when using the inbuild VODPlayer, the chat is not working anymore. I only see the latest frame of the chat and nothing more. 

When setting chat delay to 0 or to the capture difference it does not make any difference. 

![image](https://user-images.githubusercontent.com/84481241/209575631-8bcea565-fa39-4b06-8cc9-ef29c04f32b4.png)

**Here you can see the beginning of the vod, but the chat is showing the goodby texts (ending of the stream)**
![image](https://user-images.githubusercontent.com/84481241/209575758-a62d2a11-afb1-4cd5-920f-5d63f6d79949.png)

Can not find something about this in the logs.

[2022-12-26.log](https://github.com/MrBrax/twitch-vod-chat/files/10304501/2022-12-26.log)

Older Vods hower do work.

**The top folder is showing a new VOD, where the chat doesn't work. The lower folder is showing a older VOD where the chat does work.**
![image](https://user-images.githubusercontent.com/84481241/209576160-a8a445ff-78dd-4acb-928c-3644fe05c33a.png)

Hoping I give you enough info.

Thanks for this amazing project

**Comment by MrBrax** [comment]
hmm, not seeing this myself

**Comment by CappiSteijns** [comment]
> hmm, not seeing this myself

Is it correct that the vod player now opens within LivestreamDVR and does not open on a new tab anymore?

**Comment by MrBrax** [comment]
> > hmm, not seeing this myself
> 
> Is it correct that the vod player now opens within LivestreamDVR and does not open on a new tab anymore?

yes, it's now integrated into the main client
